<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<WSMatching xmlns="http://www.kth.se/ict/id2208/Matching">
    <Macthing>
        <OutputServiceName>PersonService</OutputServiceName>
        <InputServiceName>AdventureRuralareaService</InputServiceName>
        <MacthedOperation>
            <OutputOperationName>get_PERSON</OutputOperationName>
            <InputOperationName>get_RURALAREA</InputOperationName>
            <OpScore>0.5</OpScore>
            <MacthedElement>
                <OutputElement>PersonType</OutputElement>
                <InputElement>AdventureType</InputElement>
                <Score>0.5</Score>
            </MacthedElement>
        </MacthedOperation>
        <WsScore>0.5</WsScore>
    </Macthing>
</WSMatching>
