<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<WSMatching xmlns="http://www.kth.se/ict/id2208/Matching">
    <Macthing>
        <OutputServiceName>PersonService</OutputServiceName>
        <InputServiceName>AuthorMonographpriceService</InputServiceName>
        <MacthedOperation>
            <OutputOperationName>get_PERSON</OutputOperationName>
            <InputOperationName>get_MONOGRAPH_PRICE</InputOperationName>
            <OpScore>0.6</OpScore>
            <MacthedElement>
                <OutputElement>PersonType</OutputElement>
                <InputElement>AuthorType</InputElement>
                <Score>0.6</Score>
            </MacthedElement>
        </MacthedOperation>
        <WsScore>0.6</WsScore>
    </Macthing>
</WSMatching>
