<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<WSMatching xmlns="http://www.kth.se/ict/id2208/Matching">
    <Macthing>
        <OutputServiceName>Academic-item-numberBookauthorService</OutputServiceName>
        <InputServiceName>AuthorNovelmaxpriceService</InputServiceName>
        <MacthedOperation>
            <OutputOperationName>get_BOOK_AUTHOR</OutputOperationName>
            <InputOperationName>get_NOVEL_MAXPRICE</InputOperationName>
            <OpScore>1.0</OpScore>
            <MacthedElement>
                <OutputElement>AuthorType</OutputElement>
                <InputElement>AuthorType</InputElement>
                <Score>1.0</Score>
            </MacthedElement>
        </MacthedOperation>
        <WsScore>1.0</WsScore>
    </Macthing>
</WSMatching>
