<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<WSMatching xmlns="http://www.kth.se/ict/id2208/Matching">
    <Macthing>
        <OutputServiceName>ACHWorksWS</OutputServiceName>
        <InputServiceName>SubscriberInfoWSService</InputServiceName>
        <MacthedOperation>
            <OutputOperationName>SendACHTrans</OutputOperationName>
            <InputOperationName>exportAllRecords</InputOperationName>
            <OpScore>0.9355069850316177</OpScore>
            <MacthedElement>
                <OutputElement>FileName</OutputElement>
                <InputElement>fileName</InputElement>
                <Score>0.9355069850316177</Score>
            </MacthedElement>
        </MacthedOperation>
        <MacthedOperation>
            <OutputOperationName>GetErrorFile</OutputOperationName>
            <InputOperationName>exportAllRecords</InputOperationName>
            <OpScore>0.9355069850316177</OpScore>
            <MacthedElement>
                <OutputElement>FileName</OutputElement>
                <InputElement>fileName</InputElement>
                <Score>0.9355069850316177</Score>
            </MacthedElement>
        </MacthedOperation>
        <MacthedOperation>
            <OutputOperationName>SendIATACHTransBatch</OutputOperationName>
            <InputOperationName>exportAllRecords</InputOperationName>
            <OpScore>0.9355069850316177</OpScore>
            <MacthedElement>
                <OutputElement>FileName</OutputElement>
                <InputElement>fileName</InputElement>
                <Score>0.9355069850316177</Score>
            </MacthedElement>
        </MacthedOperation>
        <MacthedOperation>
            <OutputOperationName>SendACHTransBatch</OutputOperationName>
            <InputOperationName>exportAllRecords</InputOperationName>
            <OpScore>0.9355069850316177</OpScore>
            <MacthedElement>
                <OutputElement>FileName</OutputElement>
                <InputElement>fileName</InputElement>
                <Score>0.9355069850316177</Score>
            </MacthedElement>
        </MacthedOperation>
        <MacthedOperation>
            <OutputOperationName>SendACHTransBatchBin</OutputOperationName>
            <InputOperationName>exportAllRecords</InputOperationName>
            <OpScore>0.9355069850316177</OpScore>
            <MacthedElement>
                <OutputElement>FileName</OutputElement>
                <InputElement>fileName</InputElement>
                <Score>0.9355069850316177</Score>
            </MacthedElement>
        </MacthedOperation>
        <MacthedOperation>
            <OutputOperationName>GetResultFile</OutputOperationName>
            <InputOperationName>exportAllRecords</InputOperationName>
            <OpScore>0.9355069850316177</OpScore>
            <MacthedElement>
                <OutputElement>FileName</OutputElement>
                <InputElement>fileName</InputElement>
                <Score>0.9355069850316177</Score>
            </MacthedElement>
        </MacthedOperation>
        <MacthedOperation>
            <OutputOperationName>DeleteACHTransBatch</OutputOperationName>
            <InputOperationName>exportAllRecords</InputOperationName>
            <OpScore>0.9355069850316177</OpScore>
            <MacthedElement>
                <OutputElement>FileName</OutputElement>
                <InputElement>fileName</InputElement>
                <Score>0.9355069850316177</Score>
            </MacthedElement>
        </MacthedOperation>
        <WsScore>0.9355069850316176</WsScore>
    </Macthing>
</WSMatching>
