/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'johan' at '3/2/17 12:02 PM' with Gradle 3.1
 *
 * @author johan, @date 3/2/17 12:02 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
